sub: # 注有#的是失效的订阅链接
  - https://fq.lonxin.net/clash/proxies
# - https://122.10.97.150/clash/proxies
  - https://free.dswang.ga/clash/proxies
  - https://proxies.bihai.cf/clash/proxies
  - https://proxy.yugogo.xyz/clash/proxies
  - https://ss.dswang.ga:8443/clash/proxies
  - https://klausvpn.posyao.com/clash/proxies
  - https://proxypoolss.fly.dev/clash/proxies
  - https://sspool.herokuapp.com/clash/proxies
  - https://proxypool.laowang.me/clash/proxies
  - https://free886.herokuapp.com/clash/proxies
  - https://proxypool.remon602.ga/clash/proxies
  - https://us-proxypool.herokuapp.com/clash/proxies
